language: php
php:
  - 7.0
  - 5.6
  - 5.5


matrix:
  allow_failures:
    - php: 7.0

services: mysql


before_script:
  - mysql -e 'create database myapp_test;'
  - cp  .travis.parameters_test.mysql.yml  app/config/parameters.yml
  - cp  .travis.parameters_test.mysql.yml  app/config/parameters_test.yml
  - cp  app/phpunit.xml.dist  app/phpunit.xml
  - composer install --dev --no-interaction


script: phpunit  --configuration app/phpunit.xml


