slight_scribe_homepage:
    path:     /
    defaults: { _controller: SlightScribeBundle:Default:index }

########################################### ADMIN
slight_scribe_admin_homepage:
    path:     /admin/
    defaults: { _controller: SlightScribeBundle:Admin:index }

slight_scribe_admin_new_project:
    path:     /admin/newproject/
    defaults: { _controller: SlightScribeBundle:Admin:newProject }


slight_scribe_admin_projects_list:
    path:     /admin/project/
    defaults: { _controller: SlightScribeBundle:Admin:projects }


slight_scribe_admin_project_show:
    path:     /admin/project/{projectId}
    defaults: { _controller: SlightScribeBundle:AdminProject:index }

slight_scribe_admin_project_versions_published_list:
    path:     /admin/project/{projectId}/versionpublished
    defaults: { _controller: SlightScribeBundle:AdminProject:versionsPublished }


slight_scribe_admin_project_versions_list:
    path:     /admin/project/{projectId}/version
    defaults: { _controller: SlightScribeBundle:AdminProject:versions }

slight_scribe_admin_project_version_show:
    path:     /admin/project/{projectId}/version/{versionId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersion:index }


slight_scribe_admin_project_version_publish:
    path:     /admin/project/{projectId}/version/{versionId}/publish
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionEdit:publish }


slight_scribe_admin_project_version_new_file:
    path:     /admin/project/{projectId}/version/{versionId}/new/file
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionEdit:newFile }

slight_scribe_admin_project_version_new_version:
    path:     /admin/project/{projectId}/version/{versionId}/new/version
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionEdit:newVersion }

slight_scribe_admin_project_version_new_communication:
    path:     /admin/project/{projectId}/version/{versionId}/new/communication
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionEdit:newCommunication }


slight_scribe_admin_project_version_communications_list:
    path:     /admin/project/{projectId}/version/{versionId}/communication
    defaults: { _controller: SlightScribeBundle:AdminProjectVersion:communications }

slight_scribe_admin_project_version_communication_show:
    path:     /admin/project/{projectId}/version/{versionId}/communication/{communicationId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionCommunication:index }

slight_scribe_admin_project_version_communication_edit:
    path:     /admin/project/{projectId}/version/{versionId}/communication/{communicationId}/edit
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionCommunicationEdit:edit }

slight_scribe_admin_project_version_communication_preview:
    path:     /admin/project/{projectId}/version/{versionId}/communication/{communicationId}/preview
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionCommunicationEdit:preview }

slight_scribe_admin_project_version_communication_edit_files:
    path:     /admin/project/{projectId}/version/{versionId}/communication/{communicationId}/edit/files
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionCommunicationEdit:editFiles }

slight_scribe_admin_project_version_communication_attachment_show:
    path:     /admin/project/{projectId}/version/{versionId}/communication/{communicationId}/attachment/{attachmentId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionCommunicationAttachment:index }

slight_scribe_admin_project_version_access_points_list:
    path:     /admin/project/{projectId}/version/{versionId}/accesspoint
    defaults: { _controller: SlightScribeBundle:AdminProjectVersion:accessPoints }

slight_scribe_admin_project_version_access_point_show:
    path:     /admin/project/{projectId}/version/{versionId}/accesspoint/{accessPointId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionAccessPoint:index }

slight_scribe_admin_project_version_access_point_edit:
    path:     /admin/project/{projectId}/version/{versionId}/accesspoint/{accessPointId}/edit
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionAccessPointEdit:edit }

slight_scribe_admin_project_version_access_point_edit_fields:
    path:     /admin/project/{projectId}/version/{versionId}/accesspoint/{accessPointId}/edit/fields
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionAccessPointEdit:editFields }

slight_scribe_admin_project_version_access_point_edit_files:
    path:     /admin/project/{projectId}/version/{versionId}/accesspoint/{accessPointId}/edit/files
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionAccessPointEdit:editFiles }

slight_scribe_admin_project_version_runs_list:
    path:     /admin/project/{projectId}/version/{versionId}/run
    defaults: { _controller: SlightScribeBundle:AdminProjectVersion:runs }

slight_scribe_admin_project_version_run_show:
    path:     /admin/project/{projectId}/version/{versionId}/run/{runId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionRun:index }

slight_scribe_admin_project_version_files_list:
    path:     /admin/project/{projectId}/version/{versionId}/file
    defaults: { _controller: SlightScribeBundle:AdminProjectVersion:files }

slight_scribe_admin_project_version_file_show:
    path:     /admin/project/{projectId}/version/{versionId}/file/{fileId}
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionFile:index }

slight_scribe_admin_project_version_file_edit:
    path:     /admin/project/{projectId}/version/{versionId}/file/{fileId}/edit
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionFileEdit:edit }

slight_scribe_admin_project_version_file_preview:
    path:     /admin/project/{projectId}/version/{versionId}/file/{fileId}/preview
    defaults: { _controller: SlightScribeBundle:AdminProjectVersionFileEdit:preview }

slight_scribe_admin_project_fields_list:
    path:     /admin/project/{projectId}/fields
    defaults: { _controller: SlightScribeBundle:AdminProject:fields }

slight_scribe_admin_project_new_field_text:
    path:     /admin/project/{projectId}/newfield/text
    defaults: { _controller: SlightScribeBundle:AdminProjectEdit:newFieldText }

slight_scribe_admin_project_new_field_textarea:
    path:     /admin/project/{projectId}/newfield/textarea
    defaults: { _controller: SlightScribeBundle:AdminProjectEdit:newFieldTextArea }

slight_scribe_admin_project_new_field_date:
    path:     /admin/project/{projectId}/newfield/date
    defaults: { _controller: SlightScribeBundle:AdminProjectEdit:newFieldDate }

slight_scribe_admin_block_ip_list:
    path:     /admin/block/ip/
    defaults: { _controller: SlightScribeBundle:Admin:blockIPs }

slight_scribe_admin_block_ip_show:
    path:     /admin/block/ip/{blockId}
    defaults: { _controller: SlightScribeBundle:AdminBlockIP:index }

slight_scribe_admin_block_email_list:
    path:     /admin/block/email/
    defaults: { _controller: SlightScribeBundle:Admin:blockEmails }

slight_scribe_admin_block_email_show:
    path:     /admin/block/email/{blockId}
    defaults: { _controller: SlightScribeBundle:AdminBlockEmail:index }


########################################### USER

slight_scribe_project_run_create:
    path:     /project/{projectId}/run
    defaults: { _controller: SlightScribeBundle:Project:create }

slight_scribe_project_run_create_widget:
    path:     /project/{projectId}/runWidget
    defaults: { _controller: SlightScribeBundle:Project:createWidget }


slight_scribe_project_run_stop:
    path:     /project/{projectId}/stop/{runId}/{securityKey}
    defaults: { _controller: SlightScribeBundle:ProjectRun:stop }


slight_scribe_project_run_file:
    path:     /project/{projectId}/file/{runId}/{securityKey}/{fileId}
    defaults: { _controller: SlightScribeBundle:ProjectRun:file }


######################################################################## API 1

questionkey_api_1_project_data_json:
    pattern:  /api/v1/project/{projectId}/data.json
    defaults: { _controller: SlightScribeBundle:API1Project:dataJSON }
    methods:  [GET]

questionkey_api_1_project_data_jsonp:
    pattern:  /api/v1/project/{projectId}/data.jsonp
    defaults: { _controller: SlightScribeBundle:API1Project:dataJSONP }
    methods: [GET]

questionkey_api_1_project_action_json:
    pattern:  /api/v1/project/{projectId}/action.json
    defaults: { _controller: SlightScribeBundle:API1Project:actionJSON }
    methods:  [POST]

questionkey_api_1_project_action_jsonp:
    pattern:  /api/v1/project/{projectId}/action.jsonp
    defaults: { _controller: SlightScribeBundle:API1Project:actionJSONP }
    methods: [POST]
