services:
#    simple_letter.example:
#        class: SlightScribeBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    my.listener:
        class: SlightScribeBundle\EventListener\PrePersistEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
